#!/bin/bash
# author: ph-u
# script: db
# desc: prepare blastdb in chunks of 750 genomes
# in: bash db *_[overall accession list]
# out: data/*_[overall accession list].nb*
# arg: 1
# date: 20250224

bNam=`basename $1 | rev | sed -e "s/[.]/@/" | cut -f 2 -d "@" | rev`
[[ -f ${bNam}.fa ]]&&rm ${bNam}.fa
mkdir -p ../data/${bNam}

if [[ `wc -l < $1` != `ls ../data/${bNam} | wc -l` ]];then
  touch ${bNam}.fa

  datasets download genome accession `cat $1` --dehydrated --include genome --filename ${bNam}.zip && unzip ${bNam}.zip -d ../data/${bNam}_r && datasets rehydrate --directory ../data/${bNam}_r/

  for i in `find ../data/${bNam}_r/ | grep -e "_genomic.fna$"`;do
    mv ${i} ../data/${bNam}/
  done
  rm -r ../data/${bNam}_r
  cat ../data/${bNam}/* > ${bNam}.fa

  makeblastdb -in ${bNam}.fa -dbtype nucl -parse_seqids -out ../data/${bNam} -title ${bNam} # singularity binding home directory
  rm ${bNam}.fa
fi
exit
