#!/bin/env bash
# author: ph-u
# script: dbfa
# desc: ORF identification (fuse and modify blastn_c.sh & dbSum_c.sh)
# in: dbfa [line number for a gene]
# out: NA
# arg: 2
# date: 20250222

tID=$1
i2=`head -n ${tID} iDx-selected.csv | tail -n 1`
aCc=`echo -e "${i2}" | cut -f 1 -d ","` # Acc_locus, at ${CWD}
lSt=`echo -e "${i2}" | cut -f 2 -d ","`
lEd=`echo -e "${i2}" | cut -f 3 -d ","`
lOcNam=`echo -e "${lSt}${lEd}"`
lOc=`grep -e "${lSt},${lEd}" ../data/${aCc}_cds-flanking.csv | cut -f 2 -d ","`

touch ../data/noHit.log
dbNum=`wc -l < ../data/iDx.txt`

##### query sequence from reference genome #####
## grab sequence by location on cds file
tail -n +`grep -n ${lSt} ../data/${aCc}_cds.fa | grep -e ${lEd} | grep -e ${lOc} | cut -f 1 -d ":"` ../data/${aCc}_cds.fa | head -n 2 > ../data/${aCc}-${lOc}+${lOcNam}.fa
rawCDS="../data/${aCc}-${lOc}+${lOcNam}.fa"

##### dN/dS data extraction #####
echo -e "`whereis Rscript`" > /dev/null # for some reason this echo line "wakes" container to use the R & lib path inside the container instead of host system
cd /binHPC2

max_jobs=24; cur_jobs=0
for i4 in `seq 1 ${dbNum}`;do
  ((cur_jobs >= max_jobs)) && wait -n # traffic control

## set filenames
    i0="../data/${aCc}-${lOc}+${lOcNam}-${i4}_db.fa"
    i3="../data/${aCc}-${lOc}+${lOcNam}-${i4}.txt"

    i1=`head -n ${i4} ../data/iDx.txt | tail -n 1`
    echo -e "`date` - ${i1}: ${i4} / ${dbNum}"

## blast
    blastn -query ${rawCDS} -db ../data/`echo -e "${i1}" | rev | cut -f 1 -d "/" | rev` -out ${i3} -outfmt "6 delim=@ qseqid sseqid sstart send sstrand sseq" -max_target_seqs $(( `ls ../data/${i1}/ | wc -l` *2 )) -subject_besthit
   if [[ `grep -e "@" ${i3} | wc -l` -gt 0 ]];then
      Rscript blastn2faByGene.r ${i3} ${rawCDS} ${i4} && rm ${i3} & ((++cur_jobs)) # https://stackoverflow.com/questions/42211173/bash-script-to-run-a-constant-number-of-jobs-in-the-background
   else
      echo -e "${aCc};${lOcNam};`echo -e "${i1}" | rev | cut -f 1 -d "/" | rev`" >> ../data/noHit.log
   fi
done;wait

[[ -f ${rawCDS} ]]&&rm ${rawCDS}
exit
