#!/bin/env bash
# author: ph-u
# script: dbsum
# desc: Whole gene dN/dS calculation
# in: dbsum [order within a `_db.fa` list] [-xsp (optional)]
# out: NA
# arg: 1
# date: 20250813

i0=`ls ../data/*_db.fa | head -n $1 | tail -n 1`
echo -e "`whereis Rscript`" > /dev/null
cd /binHPC2

if [[ $2 -eq "-xsp" ]];then
  Rscript dbSum.r ${i0} -xsp
else
  Rscript dbSum.r ${i0}
fi
exit
