#!/bin/env bash
# author: ph-u
# script: dbsum
# desc: Whole gene dN/dS calculation
# in: dbsum [order within a `_db.fa` list]
# out: NA
# arg: 1
# date: 20250813

i0=`ls ../data/*_db.fa | head -n $1 | tail -n 1`
Rscript dbSum.r ${i0}

exit
