#!/bin/bash
# author: ph-u
# script: ref
# desc: download and reformat reference genomes
# in: ref [../path/2/refGenome].txt
# out: [acc1]_{cds,flanking,genome}.*
# arg: 1
# date: 20250223

datasets download genome accession `cat $1` --include cds,gff3,genome --filename ncbi_ref.zip && unzip ncbi_ref.zip -d ../data/ && rm ../data/{README.md,md5sum.txt} && mv ../data/ncbi_dataset ncbi_ref && rm ncbi_ref.zip
[[ -f README.md ]]&&rm README.md
[[ -f md5sum.txt ]]&&rm md5sum.txt
[[ -f iDx.csv ]]&&rm iDx.csv
touch iDx.csv

while read -r L;do
    L0=`echo -e "${L}" | sed -e "s/[.]//g" -e "s/_//g"`
    cp ncbi_ref/data/${L}/genomic.gff ../data/${L0}_genomic.gff
    bash 00_ffn2fa.sh ncbi_ref/data/${L}/cds_from_genomic.fna ../data/${L0}_cds
    bash 00_ffn2fa.sh `ls ncbi_ref/data/${L}/${L}*` ../data/${L0}_genomic
    bash gFlanking.sh ../data/${L0}_cds.fa ../data/${L0}_genomic.fa
    cat ../data/${L0}_cds-flanking.csv | cut -f 2 -d "," > ../data/${L0}_iDx.csv
    while read -r L1;do
        echo -e "${L0}_${L1}" >> iDx.csv
    done < ../data/${L0}_iDx.csv
    rm ../data/${L0}_iDx.csv
done < $1

cat iDx.csv | cut -f 1 -d "_" | sort | uniq -c > ../data/freqSLURM.txt
cp iDx.csv iDx-selected.csv
rm -r ncbi_ref
exit
